# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Producer

# Model Form Field configuration
form: $/godspeed/flametreecms/models/producer/fields.yaml

# Model Class name
modelClass: GodSpeed\FlametreeCMS\Models\Producer

# Default redirect location
defaultRedirect: godspeed/flametreecms/producers

# Create page
create:
    title: Create Producer
    redirect: godspeed/flametreecms/producers/update/:id
    redirectClose: godspeed/flametreecms/producers

# Update page
update:
    title: Edit Producer
    redirect: godspeed/flametreecms/producers
    redirectClose: godspeed/flametreecms/producers

# Preview page
preview:
    title: Preview Producer
