faq_categories:
    label: Faq Category
    view:
        list: $/godspeed/flametreecms/models/faqcategory/columns.yaml
        toolbarButtons: add|remove|create
    manage:
        form: $/godspeed/flametreecms/models/faqcategory/modal_fields.yaml
        list: $/godspeed/flametreecms/models/faqcategory/columns.yaml

