# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Faq

# Model Form Field configuration
form: $/godspeed/flametreecms/models/faq/fields.yaml

# Model Class name
modelClass: GodSpeed\FlametreeCMS\Models\Faq

# Default redirect location
defaultRedirect: godspeed/flametreecms/faqs

# Create page
create:
    title: Create Faq
    redirect: godspeed/flametreecms/faqs/update/:id
    redirectClose: godspeed/flametreecms/faqs

# Update page
update:
    title: Edit Faq
    redirect: godspeed/flametreecms/faqs
    redirectClose: godspeed/flametreecms/faqs

# Preview page
preview:
    title: Preview Faq
