# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Video Playlist

# Model Form Field configuration
form: $/godspeed/flametreecms/models/videoplaylist/fields.yaml

# Model Class name
modelClass: GodSpeed\FlametreeCMS\Models\VideoPlaylist

# Default redirect location
defaultRedirect: godspeed/flametreecms/videoplaylist

# Create page
create:
    title: Create Video Playlist
    redirect: godspeed/flametreecms/videoplaylist/update/:id
    redirectClose: godspeed/flametreecms/videoplaylist

# Update page
update:
    title: Edit Video Playlist
    redirect: godspeed/flametreecms/videoplaylist
    redirectClose: godspeed/flametreecms/videoplaylist

# Preview page
preview:
    title: Preview Video Playlist
