videos:
    label: Video
    manage:
        form: $/godspeed/flametreecms/models/video/fields.yaml
        showCheckboxes: true
    view:
        list: $/godspeed/flametreecms/models/video/columns.yaml
        toolbarButtons: create|delete
        showCheckboxes: true

