# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Meeting

# Model Form Field configuration
form: $/godspeed/flametreecms/models/meeting/fields.yaml

# Model Class name
modelClass: GodSpeed\FlametreeCMS\Models\Meeting

# Default redirect location
defaultRedirect: godspeed/flametreecms/meetings

# Create page
create:
    title: Create Meeting
    redirect: godspeed/flametreecms/meetings/update/:id
    redirectClose: godspeed/flametreecms/meetings

# Update page
update:
    title: Edit Meeting
    redirect: godspeed/flametreecms/meetings
    redirectClose: godspeed/flametreecms/meetings

# Preview page
preview:
    title: Preview Meeting
