scopes:
    range:
        label: Event Date Range
        modelClass: GodSpeed\FlametreeCMS\Models\Meeting
        type: daterange
        conditions:  started_at >= ":after" AND ended_at <= ":before"

