# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Faq Category

# Model Form Field configuration
form: $/godspeed/flametreecms/models/faqcategory/fields.yaml

# Model Class name
modelClass: GodSpeed\FlametreeCMS\Models\FaqCategory

# Default redirect location
defaultRedirect: godspeed/flametreecms/faqcategories

# Create page
create:
    title: Create Faq Category
    redirect: godspeed/flametreecms/faqcategories/update/:id
    redirectClose: godspeed/flametreecms/faqcategories

# Update page
update:
    title: Edit Faq Category
    redirect: godspeed/flametreecms/faqcategories
    redirectClose: godspeed/flametreecms/faqcategories

# Preview page
preview:
    title: Preview Faq Category
