import:
    title: Import volunteers
    modelClass: GodSpeed\FlametreeCMS\Models\VolunteerImport
    list: $/godspeed/flametreecms/controllers/volunteers/columns.yaml
    view: $/godspeed/flametreecms/controllers/volunteers/import.htm

export:
    title: Export Volunteers
    modelClass: GodSpeed\FlametreeCMS\Models\VolunteerExport
    list: $/godspeed/flametreecms/controllers/volunteers/columns.yaml
