# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Video

# Model Form Field configuration
form: $/godspeed/flametreecms/models/video/fields.yaml

# Model Class name
modelClass: GodSpeed\FlametreeCMS\Models\Video

# Default redirect location
defaultRedirect: godspeed/flametreecms/video

# Create page
create:
    title: Create Video
    redirect: godspeed/flametreecms/video/update/:id
    redirectClose: godspeed/flametreecms/video

# Update page
update:
    title: Edit Video
    redirect: godspeed/flametreecms/video
    redirectClose: godspeed/flametreecms/video

# Preview page
preview:
    title: Preview Video
