# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Faq Category

# Model Form Field configuration
form: $/godspeed/essentials/models/faqcategory/fields.yaml

# Model Class name
modelClass: GodSpeed\Essentials\Models\FaqCategory

# Default redirect location
defaultRedirect: godspeed/essentials/faqcategories

# Create page
create:
    title: Create Faq Category
    redirect: godspeed/essentials/faqcategories/update/:id
    redirectClose: godspeed/essentials/faqcategories

# Update page
update:
    title: Edit Faq Category
    redirect: godspeed/essentials/faqcategories
    redirectClose: godspeed/essentials/faqcategories

# Preview page
preview:
    title: Preview Faq Category
