# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Product Category

# Model Form Field configuration
form: $/godspeed/flametreecms/models/productcategory/fields.yaml

# Model Class name
modelClass: GodSpeed\FlametreeCMS\Models\ProductCategory

# Default redirect location
defaultRedirect: godspeed/flametreecms/productcategories

# Create page
create:
    title: Create Product Category
    redirect: godspeed/flametreecms/productcategories/update/:id
    redirectClose: godspeed/flametreecms/productcategories

# Update page
update:
    title: Edit Product Category
    redirect: godspeed/flametreecms/productcategories
    redirectClose: godspeed/flametreecms/productcategories

# Preview page
preview:
    title: Preview Product Category
